In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0  0.584230 -0.962625 -0.532545
1  1.201294 -0.886011  1.407372
2 -1.574019 -1.461601 -1.639567
3 -1.583866  0.634557 -1.887312

In [16]:
dframe2

Y         Q         X
0  1.425354  2.349504 -0.237747
1 -0.297598 -0.746030 -1.006204
2 -1.433195  0.677437 -0.645178

In [17]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.584230 -0.962625 -0.532545
1       NaN  1.201294 -0.886011  1.407372
2       NaN -1.574019 -1.461601 -1.639567
3       NaN -1.583866  0.634557 -1.887312
0  2.349504 -0.237747  1.425354       NaN
1 -0.746030 -1.006204 -0.297598       NaN
2  0.677437 -0.645178 -1.433195       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.584230 -0.962625 -0.532545
1       NaN  1.201294 -0.886011  1.407372
2       NaN -1.574019 -1.461601 -1.639567
3       NaN -1.583866  0.634557 -1.887312
4  2.349504 -0.237747  1.425354       NaN
5 -0.746030 -1.006204 -0.297598       NaN
6  0.677437 -0.645178 -1.433195       NaN