In [1]:
import numpy as np

In [2]:
arr= np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
a = np.random.randn(10)
a

array([-0.75035372,  0.07272077, -0.06541813, -0.72029513,  0.51557704,
        0.10057419, -0.02156427, -0.05736167,  0.47501208,  0.20170647])

In [6]:
b= np.random.randn(10)
b

array([ 1.27825867, -0.78142896,  1.60239397,  0.74297018, -1.38571034,
       -0.58706372, -0.13867249, -0.33722363, -2.11726825, -0.31505288])

In [7]:
# Binary Functions
np.add(a,b)

array([ 0.52790495, -0.70870818,  1.53697583,  0.02267505, -0.8701333 ,
       -0.48648953, -0.16023676, -0.39458531, -1.64225617, -0.11334641])

In [8]:
np.maximum(a,b)

array([ 1.27825867,  0.07272077,  1.60239397,  0.74297018,  0.51557704,
        0.10057419, -0.02156427, -0.05736167,  0.47501208,  0.20170647])